### ISSUE TITLE
Limitations/Options for non-SP Sites

### ISSUE THREAD

**Issue by mrman5917** [msft-teams/tools#1]
When customizing this plugin with our environment, I placed our helpdesk site as one of the tabs. When viewing on mobile, the portal loads, but the desktop client just shows a blank tab. Is there additional considerations that are necessary for a non-sharepoint URL to be usable in both clients? Adding the same website in an existing team as a website functions properly.

**Comment by BobGerman** [comment]
Chances are your portal requires additional valid domains in order to load. Try running a network trace in the browser, is your solution referencing any domains not included in validDomains?

**Comment by mrman5917** [comment]
The interesting thing is that teams on a mobile device doesn’t have the same blank page issue. I’ll run a trace though and make sure I got them all, but I thought it was strange that there was different result between desktop and mobile.

**Comment by karuanag** [comment]
Hi @mrman5917 hoping you were able to resolve this issue.  Please reopen if needed.  It is expected behavior that mobile/desktop are different FWIW.
