### ISSUE TITLE
[HOMEapp]: JS throw Exception if News/Announcement features are not configured.

### ISSUE THREAD

**Issue by OGcanviz** [msft-teams/tools#17]
@arun-msft JS will throw Exception if News/Announcement features are not configured. 
![image](https://user-images.githubusercontent.com/31479832/87907096-85633d00-ca96-11ea-8a5e-16788929437f.png)
![image](https://user-images.githubusercontent.com/31479832/87907118-8f853b80-ca96-11ea-8c51-36148573e14a.png)

**Comment by Saikrishna-MSFT** [comment]
@OGcanviz 
Please ensure to install in the company communicator for Announcements and get the Notification table SAS URL and update in the appsettings.json for the key called - "StorageTableEndPoint"

News component:
Create a SharePoint page with news web part, publish it. then add news link to the site.
then make use of feed intend viewer to get the list id for the news web part. update the List id on the appsettings.json.
Please ensure to create a SharePoint app to access the content of the site and update the values for the following in the appsettings.json.
SharePointClientId
AppSecret
Resource

**Comment by Saikrishna-MSFT** [comment]
> @OGcanviz
> Please ensure to install in the company communicator for Announcements and get the Notification table SAS URL and update in the appsettings.json for the key called - "StorageTableEndPoint"
> 
> News component:
> Create a SharePoint page with news web part, publish it. then add news link to the site.
> then make use of feed intend viewer to get the list id for the news web part. update the List id on the appsettings.json.
> Please ensure to create a SharePoint app to access the content of the site and update the values for the following in the appsettings.json.
> SharePointClientId
> AppSecret
> Resource

Register app at
https://<SharePointSiteUrl>/_layouts/15/appregnew.aspx

Add required permission to the app at
https://<SharePointSiteUrl>/_layouts/15/appinv.aspx

<AppPermissionRequests AllowAppOnlyPolicy="true">
    <AppPermissionRequest Scope="http://sharepoint/content/sitecollection/web" Right="Read" />
</AppPermissionRequests>

Verify the app at
https://<SharePointSiteUrl>/_layouts/15/appprincipals.aspx

**Comment by Saikrishna-MSFT** [comment]
Please follow the above mentioned steps for configuring the news/announcements sections.

**Comment by Saikrishna-MSFT** [comment]
@tinsheep , Thanks for your inputs, Indexes have been updated accordingly.
