### ISSUE TITLE
[HomeApp]: It is better if there are descriptions about the parameters of SharePoint.

### ISSUE THREAD

**Issue by OGcanviz** [msft-teams/tools#18]
@arun-msft  It is better if there are descriptions about the parameters of SharePoint.
![image](https://user-images.githubusercontent.com/31479832/87911265-eb06f780-ca9d-11ea-9b06-07eb50bc39f4.png)

**Comment by Saikrishna-MSFT** [comment]
Thanks for the feedback, added the descriptions.
