### ISSUE TITLE
[Home App]: The App authorization can't work normal if we haven't enable implicit grant flow.

### ISSUE THREAD

**Issue by OGcanviz** [msft-teams/tools#19]
@arun-msft There is a section describing how to register Home App with Azure AD, but it lacks steps to describe how to enable implicit grant flow.
![image](https://user-images.githubusercontent.com/31479832/87912210-8ba9e700-ca9f-11ea-868f-4b0f1472b2df.png)

**Comment by Saikrishna-MSFT** [comment]
updated README.md file with the steps to enable the implicit grant.
