### ISSUE TITLE
Sites are not loading within Teams, "Go To Website" for Tab works fine

### ISSUE THREAD

**Issue by lukepfaff** [msft-teams/tools#2]
I have modified and deployed the App to Teams.  When you navigate the tabs in the app none of the sites load within the Teams client.  But if I choose the "Go to website" option for the tab the site loads as expected so I am confident that I have the right url and user rights.  This is the same for both SharePoint Online sites and public websites like the Coffee in the Cloud youtube site.

When opening the app from the Web Client everything works just fine.  This is only when using the desktop client.

**Comment by ze1000** [comment]
I have the same issue. There was one site that I published that rendered, but no other within the app. No problems to render the pages on the browser version of teams.

**Comment by martinliljenberg** [comment]
I have the same problem. Is this related to conditional access? Is there any workaround?

**Comment by randeazy** [comment]
Same problem here. Pages work fine when using Go To Website, and are working fine in Teams webbased solution. Just the desktop side is failing to load the pages.
A random public website is working fine as a separate tab, just the SharePoint ones not.
Any idea?

**Comment by randeazy** [comment]
> Same problem here. Pages work fine when using Go To Website, and are working fine in Teams webbased solution. Just the desktop side is failing to load the pages.
> A random public website is working fine as a separate tab, just the SharePoint ones not.
> Any idea?

Manage to fix it by adding our tenant site domain in to the manifest as a "validDomains"

**Comment by martinliljenberg** [comment]
Thansk for that randeazy, that didn't help for me though. adding tenantname.onmicrosoft.com what does help is logging in another tab for example to sharepoint from a tab in a team then it works for the app as well until I log out. Did you put in the tenant site domain in the format that I tried or differently? Perhaps there is a difference.

**Comment by randeazy** [comment]
> Thansk for that randeazy, that didn't help for me though. adding tenantname.onmicrosoft.com what does help is logging in another tab for example to sharepoint from a tab in a team then it works for the app as well until I log out. Did you put in the tenant site domain in the format that I tried or differently? Perhaps there is a difference.

Hou have to idd the root site COLLECTION like tenantname.sharepoint.com

**Comment by martinliljenberg** [comment]
no I added tenant.onmicroft.com will try this as well

**Comment by ze1000** [comment]
I tried that and it didn't work. Tried adding the tenant collection domain and removing all other ones as well, and still no luck.

**Comment by BobGerman** [comment]
For SharePoint sites like Learning Pathways, try adding the valid domains used in SP Framework:

**Comment by ze1000** [comment]
Tried it. Did not help

**Comment by joaoferreira** [comment]
Since this issue is the same of issue number 3 I'm adding here a solution to make it work https://teams.handsontek.net/2020/02/13/how-to-fix-the-authentication-issues-with-personal-apps-using-sharepoint-pages/

**Comment by karuanag** [comment]
Closing this issue as the core code has been added to this version of the app template.  Thank you.
