### ISSUE TITLE
[Home App]: It is better to add step to prompt that need admin consent permission.

### ISSUE THREAD

**Issue by OGcanviz** [msft-teams/tools#20]
@arun-msft There is a section describing how to add Microsoft Graph API permissions, it is better to add step to prompt that need admin consent permission.
![image](https://user-images.githubusercontent.com/31479832/87914180-dc6f0f00-caa2-11ea-9b79-d556592a60c0.png)

**Comment by Saikrishna-MSFT** [comment]
README.md file has been updated as per the suggestion.
