### ISSUE TITLE
[Sample Hub]: Sample Hub app icon won't show on mobile

### ISSUE THREAD

**Issue by tinsheep** [msft-teams/tools#27]
Any idea why my Sample Hub app won't show on my android phone teams app? It shows up fine in the desktop for the same user as per the setup policy. I have other custom apps show up as per the same policy on my mobile app but the Sample Hub just won't show. I tried in the beta app, production app, developer preview app on and off but no dice. TIA for any thoughts.

**Comment by arun-msft** [comment]
@tinsheep Are you using same images which is available in the solution. If yes it should work. It is working for me without any issues.

**Comment by tinsheep** [comment]
Yes - It must have something to do with my policy - when I have the hub set to auto install the app and set to the top/left and no user pinning they cant even see the app on mobile (desktop is fine). When users are not under policy they can pick the Sample Hub and then re-order it where they want so i will just do that for now. Thanks.
