### ISSUE TITLE
Add additional tabs outside of SharePoint

### ISSUE THREAD

**Issue by kemppaik** [msft-teams/tools#29]
We want to add some tabs that are outside of SharePoint into this app.  An example is to another application that is not a Microsoft product but has a secure website (https).  The other is a Microsoft Form that we want as a tab, not embedded on a SharePoint page (it doesn't keep the theme when we do this).

Is this possible?  Has anyone accomplished this, and if so, how?

**Comment by jasonwbaxter** [comment]
Hi @kemppaik  yes this is achievable , you would need to add additional Tabs and also ensure that authentication is handled. I would suggest creating an app per application first to understand how to configure and authenticate , and then try to bring them together. You may also need to have a Azure App Registration to help with the permissions etc. i would try the Hello World App to get familiar with the concepts.

https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-and-run
