### ISSUE TITLE
Getting a blank page when using the Teams client 

### ISSUE THREAD

**Issue by joaoferreira** [msft-teams/tools#3]
The app is not able to automatically authenticate the user on SharePoint. This is a major block for the use of this app and this scenario to extend Microsoft Teams and to increase the adoption by bringing SharePoint content to Teams.

The only way to make it work is by opening a SharePoint page inside the Teams client using the SharePoint app or the website app, which is not a solution because the end user do not know it has to be done.

After doing the authentication if the user closes the Teams client, the issue happens again until a new SharePoint page is opened.

If using the browser everything works fine and the authentication is shared between SharePoint and Teams, but again using the browser is not the ideal solution if we want to increase the adoption.

Tried several approaches including the ones being used by the SPFx solutions to do the authentication on modern SharePoint web parts but the result is the same and it ends up showing a blank page.

**Comment by ze1000** [comment]
Really good find! Thank you for sharing. BTW, it is the same as Issue #2

**Comment by randeazy** [comment]
Thanks for sharing. Hopefully this get fixed soon cause the possibility of getting users directly from Teams Apps into SharePoint solutions is a major step forward.

**Comment by BobGerman** [comment]
@joaoferreira did you try these valid domains (same as SPFx)?
This has fixed the problem for others, hoping it's the answer:

    "validDomains": [
        "*.login.microsoftonline.com",
        "*.sharepoint.com",
        "*.sharepoint-df.com",
        "spoppe-a.akamaihd.net",
        "spoprod-a.akamaihd.net",
        "resourceseng.blob.core.windows.net",
        "msft.spoppe.com"
      ]

Please LMK if this helps, I just submitted a PR to add them to the sample. Thanks!

**Comment by joaoferreira** [comment]
@BobGerman tried this before. 
All this domains are used by the SPFx webparts but here they don't seem to work even if you add the azure application to the manifest.

Even if this starts to work it doesn't seem to be a reliable method as we will be always dependent on the urls that microsoft uses, if they change something we will end up with a lot of customers with broken apps. 

This should be handled automatically by the teams client or at least allow us to use the SharePoint page that is being used by the SharePoint app to do the authentication.

With this being said, probably this is not the best place to report the issue since the problem is not the app but the platform.

**Comment by joaoferreira** [comment]
I managed to get this working and I wrote an article explaining what I needs to be done in the manifest of the app. @BobGerman I can clarify on this if needed to incorporate it in the solution.

https://teams.handsontek.net/2020/02/13/how-to-fix-the-authentication-issues-with-personal-apps-using-sharepoint-pages/

**Comment by karuanag** [comment]
Thank you for this contribution and the blog post.  This has been incorporated into the app.  This feedback also has made it into the other feeback channels for the service teams.
