### ISSUE TITLE
How to Export user and team chat history Microsoft Team 

### ISSUE THREAD

**Issue by anomepani** [msft-teams/tools#30]
How to Export user and team chat history Microsoft Team ?

Is there any tools, Powershell or  API available to export user's 1:1 and group chat history using app token?

**Comment by arun-msft** [comment]
https://docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0

**Comment by anomepani** [comment]
> [docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0](https://docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0)

@arun-msft  Does this feature support using application permission? 

The above link looks like related to personnel chat but not for team channel chat.
Is there a way to export full Microsoft Teams Team channel chat history?
