### ISSUE TITLE
CompanyCommunicator expiration date

### ISSUE THREAD

**Issue by valeriaqalvarenga** [msft-teams/tools#35]
I have noticed that the CompanyCommunicator sometimes disappears from the TeamsSampleHub, and this is because of the expiration date configured in Azure to generate the StorageTableEndPoint parameter. I have tried to extend the expiration date to more than a month but he ends up going back to a close date. With that, the CompanyCommunicator disappears from TeamsSampleHub in a few days.

Do you have any suggestions? 
Thank you.

**Comment by arun-msft** [comment]
You can give expiration date after one year then it will not disappear. In my case we created expiration date one year and it is working for me without any issues. Please try to give expiration date instead of one month give one year.

**Comment by valeriaqalvarenga** [comment]
Thanks. I had tried with a deadline longer than a year and the next day it stopped.
I will do it with, as you suggested. 

Thanks

**Comment by arun-msft** [comment]
@valeriaqalvarenga : HOw about this issue?

**Comment by valeriaqalvarenga** [comment]
@arun-msft: It's working now.

Thanks.
