### ISSUE TITLE
On the mobile, the Home tab works only if I open the Shifts app first

### ISSUE THREAD

**Issue by valeriaqalvarenga** [msft-teams/tools#36]
I noticed that whenever I publish a new version of TeamsSampleHub, for it to work again on my cell phone, I need to open Shifts before open SampleHub.
 
To replicate:
1) Update version of TeamsSampleHub
2) On my cell phone, I log off / log on to Teams. The  Home tab doesn't work and the loading icons do not appear. The Learning tab loads correctly.
3) Access the Shifts application.
4) I go back to SampleHub and it loads correctly.
 
Apparently SampleHub is loading only if I first access Shifts.

Any suggestions? 

Thanks.

**Comment by arun-msft** [comment]
@valeriaqalvarenga : I never faced this issue.  Did you provided required permissions on your app id, Also did you created shifts correctly in the shift application. Could you please share screen shots of your experience so that i will check and will get back to you for the same

**Comment by valeriaqalvarenga** [comment]
@arun-msft : Yes. The app's permissions are set and the shifts are created. This problem only occurs on the first access.
I will run new tests on an Android and also on an original version of SampleHub.

**Comment by arun-msft** [comment]
@valeriaqalvarenga : Still you are seeing this issue. Please give me screen shots if you are receiving still same issue.

**Comment by valeriaqalvarenga** [comment]
@arun-msft: Last Friday the customer decided not to use Shifts, so it was removed from TeamsSampleHub and the error did not occur again.

Thanks.

**Comment by arun-msft** [comment]
Thanks for the confirmation.
