### ISSUE TITLE
M365 Learning Pathways - Manifest Changes which could help deployment.

### ISSUE THREAD

**Issue by jasonwbaxter** [msft-teams/tools#41]
When deploying the app template there are a number of validation issues that show up.  how do we remove these errors.

![image](https://user-images.githubusercontent.com/68377916/98672521-9a721d80-235e-11eb-8978-11f7a42071a6.png)

**Comment by jasonwbaxter** [comment]
Even though i removed these wild cards , the manifest editor doesnt accept it until i click edit and save on the wild card domains.

**Comment by Saikrishna-MSFT** [comment]
> Even though i removed these wild cards , the manifest editor doesnt accept it until i click edit and save on the wild card domains.

Could you please let us know which manifest you're working on, as there are multiple manifests available in this repo for different purposes.

**Comment by jasonwbaxter** [comment]
For the Learning Path ways Teams App.

also change the privacy url to Aka.ms/privacy

**Comment by jasonwbaxter** [comment]
Publishing button is also disable due to these errors 
![image](https://user-images.githubusercontent.com/68377916/98916328-b814c380-24d3-11eb-98d9-5984380e5a99.png)

**Comment by arun-msft** [comment]
@jasonwbaxter : Can you try now with latest manifest and let us know still you are facing any issues? We uploaded in my demo tenant without any issues.

**Comment by jasonwbaxter** [comment]
@arun-msft  when i'm testing via the chrome browser loading app studio and importing the ZIP this is what i get.
![image](https://user-images.githubusercontent.com/68377916/99355704-7314d680-28b1-11eb-93e7-cabb95a9a1ac.png)

**Comment by jasonwbaxter** [comment]
Error while reading manifest.json: Invalid value(s) specified for validDomains[0]: "&lt;your tenant&gt;.sharepoint.com"

**Comment by jasonwbaxter** [comment]
@arun-msft  i submitted a pull request for some of the issues i'm still finding in the manifest , please check this out.

**Comment by jasonwbaxter** [comment]
Errors are still there with the latest version of the manifest , the app does install and load up fine , but the wild card domains do not allow you to publish direct from the app studio.

**Comment by arun-msft** [comment]
@jasonwbaxter : are you still seeing any issues after merging your manifest changes.

**Comment by jasonwbaxter** [comment]
@arun-msft  yes still seeing this , tried it again yesterday .. Going to submit another pull request for you.
