### ISSUE TITLE
M365 Learning Paths ways - Import Manifest error

### ISSUE THREAD

**Issue by jasonwbaxter** [msft-teams/tools#42]
![image](https://user-images.githubusercontent.com/68377916/98916810-4be68f80-24d4-11eb-9c0a-4963bbe3fc25.png)
 After re-zipping the manifest and importing it throws this error saying the manifest file is missing , but the manifest file is there in the zip folder.

**Comment by arun-msft** [comment]
@jasonwbaxter Now upload manifest and see if you are facing any issues.

**Comment by arun-msft** [comment]
Hope this issue got fixed after merging new manifest. Thanks.
