### ISSUE TITLE
M365 Learning Path Ways  - Getting Started.zip is outdated

### ISSUE THREAD

**Issue by jasonwbaxter** [msft-teams/tools#43]
Getting Started.zip is outdated still has the old manifest files.

**Comment by arun-msft** [comment]
@jasonwbaxter Updated Getting Started.zip with latest manifest files. Please check now.

**Comment by jasonwbaxter** [comment]
Still have some errors when importing the .zip

**Comment by jasonwbaxter** [comment]
@arun-msft  i submitted a pull request with some of the fixes in the manifest

**Comment by arun-msft** [comment]
merged your PR changes. Thanks for the feedback.
