### ISSUE TITLE
SampleHubReactVersion - ExtensionTabService: getAuthTokenForApp: Failed with error - App resource defined in manifest and iframe origin do not match

### ISSUE THREAD

**Issue by freederon** [msft-teams/tools#55]
When I try to install the SampleHub - React version and install the app in Teams, i can see the React loading screen, but that's it.

The console show
ExtensionTabService: getAuthTokenForApp: Failed with error - App resource defined in manifest and iframe origin do not match

I followed the steps as good as I could. To the end, the guide gets a bit unclear.
Is there a step missing in the installation guide?

Any help would be appreciated.

**Comment by Saikrishna-MSFT** [comment]
Hi @freederon ,

It seems the WebApplicationInfo in the manifest or the Application ID URI in the AAD app registration not being properly set.

WebApplicationInfo is the parent of the following elements:

id - The client ID of the application. This is the application ID that you obtained as part of registering the application with Azure AD.
resource - The domain and subdomain of your application. This is the same URI (Application ID URI - including the api:// protocol) that you registered when creating your scope in [step 5 in the Deployement section](https://github.com/msft-teams/tools/blob/master/TeamsSampleHub/SampleHubReactVersion/README.md#deployment). You must not include the access_as_user path in your resource. The domain part of this URI must match the domain, including any subdomains, used in the URLs of your Teams application manifest.

Make sure to have the correct values for the WebApplicationInfo and the Application ID URI, let us know if you still face any other issue. Thanks.

**Comment by g138** [comment]
Getting the similar issue, is there any solution for this
