### ISSUE TITLE
App doesn't show web pages in the Teams client

### ISSUE THREAD

**Issue by dirrcher** [msft-teams/tools#6]
This is still an issue, any SPO page added into the manifest fails to show in the Teams desktop client. Everything loads properly in the web client. 
The info in the 'pull requests' does not resolve the issue. The information there is mis-leading in that it states it resolves the issue when it does not.

**Comment by BigBlueHorse** [comment]
We are experiencing the same issue.  Works fine in web app, but not in Teams client app.

**Comment by dirrcher** [comment]
I managed to get this working.
Found and used this workaround, needed a little tweaking for my scenario.
![image](https://user-images.githubusercontent.com/60522573/75071227-efb18a80-54c2-11ea-9649-2588f88854c8.png)

**Comment by karuanag** [comment]
The code to auto display the SPO pages has been incorported in our current version of the template.  Please open a new issue with any further difficulty. Thank you!
